# Generated by Django 4.2.21 on 2025-08-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='recipes/images/default.jpg', null=True, upload_to='profiles/avatars/', verbose_name='Аватар'),
        ),
    ]
